export const BADGE_CATEGORIAS = {
  entrenamiento: "Entrenamiento",
  alimentacion: "Alimentación",
  medicion: "Medición",
  fuerza: "Fuerza",
  nivel: "Nivel",
  app: "Tu perfil y la app",
  combo: "Combos",
} as const;

export type BadgeCategoriaId = keyof typeof BADGE_CATEGORIAS;

export const BADGES_CATALOGO = [
  {
    codigo: "primer_entrenamiento",
    categoria: "entrenamiento" as const,
    nombre: "Primer paso",
    descripcion: "Completaste tu primer día de entrenamiento",
    icono: "🏋️",
  },
  {
    codigo: "entrenamientos_5",
    categoria: "entrenamiento" as const,
    nombre: "En marcha",
    descripcion: "5 días de entrenamiento completados",
    icono: "🏃",
  },
  {
    codigo: "entrenamientos_10",
    categoria: "entrenamiento" as const,
    nombre: "Constante",
    descripcion: "10 días de entrenamiento completados",
    icono: "💫",
  },
  {
    codigo: "entrenamientos_25",
    categoria: "entrenamiento" as const,
    nombre: "Comprometida",
    descripcion: "25 días de entrenamiento completados",
    icono: "🎯",
  },
  {
    codigo: "entrenamientos_50",
    categoria: "entrenamiento" as const,
    nombre: "Imparable",
    descripcion: "50 días de entrenamiento completados",
    icono: "⚡",
  },
  {
    codigo: "entrenamientos_75",
    categoria: "entrenamiento" as const,
    nombre: "Sin excusas",
    descripcion: "75 días de entrenamiento completados",
    icono: "🛡️",
  },
  {
    codigo: "entrenamientos_100",
    categoria: "entrenamiento" as const,
    nombre: "Centuria",
    descripcion: "100 días de entrenamiento completados",
    icono: "👑",
  },
  {
    codigo: "racha_3",
    categoria: "entrenamiento" as const,
    nombre: "Racha de 3",
    descripcion: "3 días seguidos entrenando",
    icono: "🔥",
  },
  {
    codigo: "racha_7",
    categoria: "entrenamiento" as const,
    nombre: "Una semana",
    descripcion: "7 días seguidos entrenando",
    icono: "🔥",
  },
  {
    codigo: "racha_14",
    categoria: "entrenamiento" as const,
    nombre: "Dos semanas",
    descripcion: "14 días seguidos entrenando",
    icono: "🔥",
  },
  {
    codigo: "racha_21",
    categoria: "entrenamiento" as const,
    nombre: "Tres semanas",
    descripcion: "21 días seguidos entrenando",
    icono: "🔥",
  },
  {
    codigo: "racha_28",
    categoria: "entrenamiento" as const,
    nombre: "Acero",
    descripcion: "28 días seguidos entrenando",
    icono: "💪",
  },
  {
    codigo: "desafio_completado",
    categoria: "entrenamiento" as const,
    nombre: "Desafío cumplido",
    descripcion: "Completaste tu desafío de 28 días",
    icono: "🏆",
  },
  {
    codigo: "primer_checkin",
    categoria: "alimentacion" as const,
    nombre: "Primer check-in",
    descripcion: "Registraste tu alimentación por primera vez",
    icono: "🍽️",
  },
  {
    codigo: "checkin_semana",
    categoria: "alimentacion" as const,
    nombre: "Constancia alimentaria",
    descripcion: "7 check-ins de alimentación",
    icono: "🥗",
  },
  {
    codigo: "checkin_14",
    categoria: "alimentacion" as const,
    nombre: "Dos semanas nutrición",
    descripcion: "14 check-ins de alimentación",
    icono: "🥙",
  },
  {
    codigo: "checkin_30",
    categoria: "alimentacion" as const,
    nombre: "Mes consciente",
    descripcion: "30 check-ins de alimentación",
    icono: "🌿",
  },
  {
    codigo: "checkin_60",
    categoria: "alimentacion" as const,
    nombre: "Hábito sólido",
    descripcion: "60 check-ins de alimentación",
    icono: "🍎",
  },
  {
    codigo: "checkins_cumpli_10",
    categoria: "alimentacion" as const,
    nombre: "Plan cumplido",
    descripcion: "10 días con el plan de alimentación cumplido",
    icono: "✅",
  },
  {
    codigo: "racha_alim_3",
    categoria: "alimentacion" as const,
    nombre: "Racha nutricional 3",
    descripcion: "3 días seguidos con check-in de alimentación",
    icono: "🥑",
  },
  {
    codigo: "racha_alim_7",
    categoria: "alimentacion" as const,
    nombre: "Racha nutricional 7",
    descripcion: "7 días seguidos con check-in de alimentación",
    icono: "🥑",
  },
  {
    codigo: "racha_alim_14",
    categoria: "alimentacion" as const,
    nombre: "Racha nutricional 14",
    descripcion: "14 días seguidos con check-in de alimentación",
    icono: "🥑",
  },
  {
    codigo: "primera_medicion",
    categoria: "medicion" as const,
    nombre: "Midiendo el progreso",
    descripcion: "Registraste tu primera medición",
    icono: "📏",
  },
  {
    codigo: "mediciones_3",
    categoria: "medicion" as const,
    nombre: "Seguimiento activo",
    descripcion: "3 mediciones registradas",
    icono: "📊",
  },
  {
    codigo: "mediciones_5",
    categoria: "medicion" as const,
    nombre: "Datos claros",
    descripcion: "5 mediciones registradas",
    icono: "📈",
  },
  {
    codigo: "mediciones_10",
    categoria: "medicion" as const,
    nombre: "Historial completo",
    descripcion: "10 mediciones registradas",
    icono: "📉",
  },
  {
    codigo: "pliegues_registrados",
    categoria: "medicion" as const,
    nombre: "Pliegues al día",
    descripcion: "Registraste una medición con pliegues",
    icono: "📐",
  },
  {
    codigo: "circunferencias_registradas",
    categoria: "medicion" as const,
    nombre: "Circunferencias",
    descripcion: "Registraste una medición con circunferencias",
    icono: "📏",
  },
  {
    codigo: "peso_logueado",
    categoria: "fuerza" as const,
    nombre: "Cargando fuerza",
    descripcion: "Registraste tu primer peso de ejercicio",
    icono: "🎯",
  },
  {
    codigo: "pesos_10",
    categoria: "fuerza" as const,
    nombre: "Bitácora de cargas",
    descripcion: "10 registros de peso en ejercicios",
    icono: "🏋️‍♀️",
  },
  {
    codigo: "pesos_25",
    categoria: "fuerza" as const,
    nombre: "Progresión",
    descripcion: "25 registros de peso en ejercicios",
    icono: "📈",
  },
  {
    codigo: "pesos_50",
    categoria: "fuerza" as const,
    nombre: "Levantadora",
    descripcion: "50 registros de peso en ejercicios",
    icono: "💥",
  },
  {
    codigo: "ejercicios_5_distintos",
    categoria: "fuerza" as const,
    nombre: "Variedad",
    descripcion: "Registraste peso en 5 ejercicios distintos",
    icono: "🔄",
  },
  {
    codigo: "nivel_3",
    categoria: "nivel" as const,
    nombre: "Nivel 3",
    descripcion: "Alcanzaste el nivel 3",
    icono: "✨",
  },
  {
    codigo: "nivel_5",
    categoria: "nivel" as const,
    nombre: "Nivel 5",
    descripcion: "Alcanzaste el nivel 5",
    icono: "⭐",
  },
  {
    codigo: "nivel_7",
    categoria: "nivel" as const,
    nombre: "Nivel 7",
    descripcion: "Alcanzaste el nivel 7",
    icono: "⭐",
  },
  {
    codigo: "nivel_10",
    categoria: "nivel" as const,
    nombre: "Nivel 10",
    descripcion: "Alcanzaste el nivel 10",
    icono: "🌟",
  },
  {
    codigo: "nivel_15",
    categoria: "nivel" as const,
    nombre: "Nivel 15",
    descripcion: "Alcanzaste el nivel 15",
    icono: "🌟",
  },
  {
    codigo: "nivel_20",
    categoria: "nivel" as const,
    nombre: "Nivel 20",
    descripcion: "Alcanzaste el nivel 20",
    icono: "💎",
  },
  {
    codigo: "nivel_25",
    categoria: "nivel" as const,
    nombre: "Nivel 25",
    descripcion: "Alcanzaste el nivel 25",
    icono: "💎",
  },
  {
    codigo: "evaluacion_completada",
    categoria: "app" as const,
    nombre: "Evaluación lista",
    descripcion: "Completaste tu evaluación nutricional",
    icono: "📋",
  },
  {
    codigo: "foto_perfil",
    categoria: "app" as const,
    nombre: "Cara visible",
    descripcion: "Subiste tu foto de perfil",
    icono: "📷",
  },
  {
    codigo: "onboarding_completado",
    categoria: "app" as const,
    nombre: "Bienvenida hecha",
    descripcion: "Completaste el recorrido de bienvenida",
    icono: "👋",
  },
  {
    codigo: "asistente_primer_mensaje",
    categoria: "app" as const,
    nombre: "Primera charla",
    descripcion: "Enviaste tu primer mensaje al asistente",
    icono: "💬",
  },
  {
    codigo: "asistente_10_mensajes",
    categoria: "app" as const,
    nombre: "En contacto",
    descripcion: "10 mensajes enviados al asistente",
    icono: "🤖",
  },
  {
    codigo: "asistente_checkin",
    categoria: "app" as const,
    nombre: "Check-in con coach",
    descripcion: "Registraste cómo te fue vía asistente",
    icono: "📝",
  },
  {
    codigo: "dia_completo",
    categoria: "combo" as const,
    nombre: "Día completo",
    descripcion: "Entrenamiento y check-in de alimentación el mismo día",
    icono: "🌟",
  },
  {
    codigo: "semana_equilibrada",
    categoria: "combo" as const,
    nombre: "Semana equilibrada",
    descripcion: "Al menos 3 entrenamientos y 3 check-ins en la misma semana",
    icono: "⚖️",
  },
] as const;

export type BadgeCodigo = (typeof BADGES_CATALOGO)[number]["codigo"];
