export const ALIMENTOS_SUGERENCIAS = [
  "Pollo",
  "Carne vacuna",
  "Pescado",
  "Atún",
  "Salmón",
  "Huevos",
  "Leche",
  "Yogur",
  "Queso",
  "Arroz",
  "Pasta",
  "Avena",
  "Quinoa",
  "Pan integral",
  "Papa",
  "Batata",
  "Fideos",
  "Lentejas",
  "Garbanzos",
  "Porotos",
  "Tofu",
  "Maní",
  "Almendras",
  "Nueces",
  "Aceite de oliva",
  "Palta",
  "Tomate",
  "Lechuga",
  "Espinaca",
  "Brócoli",
  "Zanahoria",
  "Cebolla",
  "Pimiento",
  "Banana",
  "Manzana",
  "Naranja",
  "Frutilla",
  "Uva",
  "Sandía",
  "Melón",
  "Yogur griego",
  "Proteína en polvo",
  "Jamón",
  "Atún en lata",
  "Sardinas",
  "Camarones",
  "Calabaza",
  "Choclo",
  "Arvejas",
  "Champiñones",
  "Pepino",
  "Apio",
  "Coliflor",
  "Repollo",
  "Kiwi",
  "Pera",
  "Durazno",
  "Ciruela",
  "Granola",
  "Miel",
  "Chocolate amargo",
  "Café",
  "Té",
  "Agua",
  "Jugo natural",
  "Smoothie",
  "Wrap integral",
  "Tortilla de trigo",
  "Hamburguesa casera",
  "Milanesa",
  "Ensalada mixta",
  "Sopa de verduras",
  "Guiso de lentejas",
  "Pizza casera",
  "Empanada al horno",
  "Sushi",
  "Cuscús",
  "Bulgur",
  "Semillas de chía",
  "Semillas de lino",
  "Manteca de maní",
  "Hummus",
  "Guacamole",
  "Salsa de tomate",
  "Mostaza",
  "Mayonesa light",
] as const;

export function filterAlimentosSugerencias(query: string, exclude: string[] = []) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  const excluded = new Set(exclude.map((item) => item.toLowerCase()));

  return ALIMENTOS_SUGERENCIAS.filter((item) => {
    const lower = item.toLowerCase();
    return lower.includes(normalized) && !excluded.has(lower);
  }).slice(0, 8);
}
