import {
  easeOutCubic,
  phaseProgressMs,
} from "@/features/auth/components/login-enter-transition";

export { easeOutCubic, phaseProgressMs };

export const EVALUACION_BRIDGE_WELCOME_HOLD_MS = 2500;
export const EVALUACION_BRIDGE_ACTIVE_MS = 2000;
export const EVALUACION_BRIDGE_HANDOFF_MS = 500;
export const EVALUACION_BRIDGE_TOTAL_MS =
  EVALUACION_BRIDGE_WELCOME_HOLD_MS +
  EVALUACION_BRIDGE_ACTIVE_MS +
  EVALUACION_BRIDGE_HANDOFF_MS;
export const EVALUACION_BRIDGE_NAVIGATE_MS = 1200;
export const EVALUACION_BRIDGE_HANDOFF_START_MS =
  EVALUACION_BRIDGE_WELCOME_HOLD_MS + EVALUACION_BRIDGE_ACTIVE_MS;
export const EVALUACION_BRIDGE_HANDOFF_MAX_WAIT_MS = 2000;
export const EVALUACION_BRIDGE_ENTER_MS = 400;
