import { Router } from "express";
import {
  aplicarPlantillaNutricionalSchema,
  createPlanNutricionalSchema,
  createPlanNutricionalTemplateSchema,
  generarBorradorPlanSchema,
  generarComidaPlanSchema,
  nutricionChatSchema,
  updatePlanNutricionalSchema,
  validarPlanNutricionalSchema,
} from "@ivisfit/database";
import { planNutricionalTemplateController } from "../controllers/plan-nutricional-template.controller.js";
import { planNutricionalController } from "../controllers/plan-nutricional.controller.js";
import { requireRole } from "../middleware/requireRole.js";
import { validateBody } from "../middleware/validate.js";
import { asyncHandler } from "../utils/asyncHandler.js";

export const planNutricionalRouter = Router();

planNutricionalRouter.get(
  "/workspace",
  requireRole("profe"),
  asyncHandler(planNutricionalController.getWorkspace),
);
planNutricionalRouter.get(
  "/gestion",
  requireRole("profe"),
  asyncHandler(planNutricionalController.listGestion),
);
planNutricionalRouter.get(
  "/mia",
  asyncHandler(planNutricionalController.getMio),
);
planNutricionalRouter.get(
  "/macros-sugeridos",
  requireRole("profe"),
  asyncHandler(planNutricionalController.getMacrosSugeridos),
);
planNutricionalRouter.get(
  "/briefing",
  requireRole("profe"),
  asyncHandler(planNutricionalController.getBriefing),
);
planNutricionalRouter.get(
  "/planes",
  requireRole("profe"),
  asyncHandler(planNutricionalController.listPlanes),
);
planNutricionalRouter.post(
  "/validar",
  requireRole("profe"),
  validateBody(validarPlanNutricionalSchema),
  asyncHandler(planNutricionalController.validatePlan),
);
planNutricionalRouter.post(
  "/clonar",
  requireRole("profe"),
  asyncHandler(planNutricionalController.clonePlan),
);
planNutricionalRouter.get(
  "/plantillas",
  requireRole("profe"),
  asyncHandler(planNutricionalTemplateController.list),
);
planNutricionalRouter.post(
  "/plantillas",
  requireRole("profe"),
  validateBody(createPlanNutricionalTemplateSchema),
  asyncHandler(planNutricionalTemplateController.create),
);
planNutricionalRouter.post(
  "/plantillas/desde-plan",
  requireRole("profe"),
  asyncHandler(planNutricionalTemplateController.createFromPlan),
);
planNutricionalRouter.post(
  "/plantillas/aplicar",
  requireRole("profe"),
  validateBody(aplicarPlantillaNutricionalSchema),
  asyncHandler(planNutricionalTemplateController.apply),
);
planNutricionalRouter.patch(
  "/plantillas/:id",
  requireRole("profe"),
  asyncHandler(planNutricionalTemplateController.update),
);
planNutricionalRouter.delete(
  "/plantillas/:id",
  requireRole("profe"),
  asyncHandler(planNutricionalTemplateController.remove),
);
planNutricionalRouter.get(
  "/generar-borrador/estado/:jobId",
  requireRole("profe"),
  asyncHandler(planNutricionalController.generateDraftStatus),
);
planNutricionalRouter.get(
  "/",
  asyncHandler(planNutricionalController.getByAlumna),
);
planNutricionalRouter.get(
  "/:id",
  asyncHandler(planNutricionalController.getById),
);
planNutricionalRouter.post(
  "/",
  requireRole("profe"),
  validateBody(createPlanNutricionalSchema),
  asyncHandler(planNutricionalController.create),
);
planNutricionalRouter.post(
  "/generar-borrador",
  requireRole("profe"),
  validateBody(generarBorradorPlanSchema),
  asyncHandler(planNutricionalController.generateDraft),
);
planNutricionalRouter.post(
  "/generar-comida",
  requireRole("profe"),
  validateBody(generarComidaPlanSchema),
  asyncHandler(planNutricionalController.generateComida),
);
planNutricionalRouter.get(
  "/generar-comida/estado/:jobId",
  requireRole("profe"),
  asyncHandler(planNutricionalController.generateComidaStatus),
);
planNutricionalRouter.post(
  "/chat",
  validateBody(nutricionChatSchema),
  asyncHandler(planNutricionalController.chat),
);
planNutricionalRouter.patch(
  "/:id",
  requireRole("profe"),
  validateBody(updatePlanNutricionalSchema),
  asyncHandler(planNutricionalController.update),
);
planNutricionalRouter.post(
  "/:id/nueva-version",
  requireRole("profe"),
  asyncHandler(planNutricionalController.createNewVersion),
);
planNutricionalRouter.post(
  "/:id/publicar",
  requireRole("profe"),
  asyncHandler(planNutricionalController.publish),
);
planNutricionalRouter.post(
  "/:id/archivar",
  requireRole("profe"),
  asyncHandler(planNutricionalController.archive),
);
planNutricionalRouter.delete(
  "/:id",
  requireRole("profe"),
  asyncHandler(planNutricionalController.remove),
);
